language: node_js
node_js:
  - "4"
  - "6"
  - "8"
addons:
  code_climate:
    repo_token:
      secure: "aD40E6+dh86c/njZFQsD7S/MO7huKqqJvxd3CTyLNNLQ26zBmdcAoRDsg4WfkPu2cR2GIXTqYt72FSFotJpoy73bEbEcMHtiXkIsu/FBs5ZhZ6nZ7C5+z68WiN0YxAOlqkgdxakTRWnaJ2A9arBkGyBqJUfzaMf+ATikZ5PCLdfEi1uehiYF8hF1lltrnF7Nd2mu0aC1p2JBEXuP2++XRea2YmJ2yEf35cwUlSjRAWOZMA7WC7RrSatbX172UNzj+yIHJm4WBdX0r8q9GD+C6Gbi7WixMXV6qSiE9qfebEGEJUAlx9Vks9aPHXoV77fCPRLCJoWxucbis8BUmTSzArNfFZT5Ap9vH1oDvCujeW0oNyki++n+mpM95OXvDujfTrO5V+eyKh3aaHEt1rkiHF33tRiVyyUYQX9oGUFZRfdIezfZKIC9FIMSa60hX2xhHV8J2xYztNk1IkDf267r8iZMEMrWKvq7fC4JwAWCqZVdgFeFY9T6j/FkjiJVMewi7QCv8R6/5Vnd5ZcOOT8vXqFvmt0t2qwkRCxGLo8voqhfDuDBqLfMisoTuaYnZ3eVsX77WfHhNisablDPu1jgyLhBgt/vqN/Vgab2L+cov0mmsYJ7g2l116fheY7ZbBVhn355VHD0+THEc3UCNv/Mv4bF4yD6ScmzKtdfFe9eNOU="
after_script:
  - npm install -g codeclimate-test-reporter
  - cat coverage/lcov.info | codeclimate
